<a href="https://colab.research.google.com/github/ragalaa/Directory/blob/master/Array_Manipulation_%26_Multi_Dimensional_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy --upgrade

     |████████████████████████████████| 20.4MB 5.1MB/s 
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:
      Successfully uninstalled numpy-1.16.5


In [0]:
import numpy as np


In [3]:
array_one  = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [4]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [5]:
## array shape 3 rows 4 columns with Zeros.
array_of_zeros = np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
## array shape 3 rows 4 columns with ones of specific type with integer.
array_of_ones_int = np.ones((3,4),dtype = np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [9]:
## Empty fucntion with shape
array_empty = np.empty((2,3),dtype = np.int16)
array_empty

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [10]:
### Square matrix 1 along diagnol with 3*3 matrix
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
### arrange to et up specific values with step fucntion with step size 2 until 20
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
## 2 Dimensional array creation with list of list with 2 rows and 3 columns
array_2d = np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [14]:
array_2d.shape

(2, 3)

In [17]:
arrange = np.arange(6)
arrange

array([0, 1, 2, 3, 4, 5])

In [19]:
### reshaping array to 3* 4 ** be care ful if you try to
### reshpe if they don't fit in it will not shape
## To test change to (3,4) requires 12 elements but it ahs only 6
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
### Array fills with same shape and prefills with Ones
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

Printing Arrays--

In [21]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
### 3 dimensional array -- Contains 2 Arrays of Size 3*4
c = np.arange(24).reshape(2,3,4)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [31]:

print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [0]:
## Inorder for the .... to move way and print all elememnts to display we can set the below option
np.set_printoptions(threshold = 10000)
# print(np.arange(10000).reshape(100,100))

Basic Numpy Operations ----

In [0]:
## Creating two one dimensional Array
## Both have same shape hence the can be added with each element

a = np.array([10,10,10])
b = np.array([5,5,5])

In [42]:
a + b

array([15, 15, 15])

In [43]:
a - b

array([5, 5, 5])

In [47]:
### If two elements has same dimension we canmultiply
## Element wise division


# a * b
a % 3

## Conditinal operator as well to dimension

a < 35

array([ True,  True,  True])

In [49]:
#### chek if all elements are  greater than 25
 a > 8

array([ True,  True,  True])

In [51]:
### mathematical operations on 2D array

A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

print( 'A:\n', A )
print( 'B:\n', B )

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


In [52]:
#### Element wise result of two dimensional array result

A * B

array([[2, 0],
       [0, 4]])

In [53]:
### matrix multiplication
## [row,col] = sum ( all elements in row * all elements in col)
### Highscj=hool match   .No of cols in first matrix A should be
### equal to no fo rows second matrix B for matrix multiplication 
## toe be possible

A.dot(B)

array([[5, 4],
       [3, 4]])

In [54]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [57]:
a  *= 3
a

array([90, 90, 90])

In [59]:
ages = np.array([12,15,18,20])
ages.sum()
ages.min()

12

In [62]:
numbers = np.arange(12).reshape(3,4)
numbers


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
## Summ along axis = 0 column's  Axis = 1 for rows1 can be sum for any 2d array
numbers.sum(axis=1)
numbers.min(axis=1)

array([0, 4, 8])

Mathematical Operations Universal Functions -- Sin, cos, tan etc..

In [67]:
### mathematical Operations will be applied to every element of the angles
## array to radians with formula pi/180

angles = np.array([0,30,45,60,90])
angles_radians = angles * np.pi/180
angles_radians


array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [68]:
print('sine of angles in array')
print( np.sin(angles_radians))

sine of angles in array
[0.         0.5        0.70710678 0.8660254  1.        ]


In [69]:
sin = np.sin( angles * np.pi/180)
print(' Compute sine inverse of angles. returned values are in radians' )
inv = np.arcsin(sin)
print(inv)

 Compute sine inverse of angles. returned values are in radians
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [70]:
### Compute angles to degrees...
print('cehck result by converting to degrees:')
print( np.degrees(inv))

cehck result by converting to degrees:
[ 0. 30. 45. 60. 90.]


In [0]:
#### Statistical scores

test_scores = np.array([32.32,56.98,21.52,44,32,
                        55.63, 13.75,43.47,43.34])

In [75]:
print('Mean test scores of students')
print(np.mean(test_scores))

Mean test scores of students
38.11222222222222


Indexing and Slicing of Arrays :----


In [79]:
## access subset of arrays..
subset = np.arange(11)**2
subset

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
subset[-2]
subset[2:7]
subset[2:-2]
subset[2:]
subset[:7]

array([ 0,  1,  4,  9, 16, 25, 36])

In [85]:
### step fucntion
### subset[:11:2]-- start:beginnning,end:11,step:2
subset[:11:2]

array([  0,   4,  16,  36,  64, 100])

In [86]:
## step in reverse direction-- REVERSE ARRAY
subset[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [87]:
## Mixed array with strings , Integers
## Dtype >>> < Little Endian ; >Big indian , U unicode
 students = np.array([['Alice','Beth','Cathy','Dorothy'],
                     ['65','78','90','81'],
                     ['71','82','79','92']])
students

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

In [88]:
students[1]

array(['65', '78', '90', '81'], dtype='<U7')

In [89]:
students[0]

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

In [90]:
students[0,1]

'Beth'

In [91]:
### Index range operations in square brackets
### 0:2 - rows >> 2:4 - cols
students[0:2,2:4]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

In [92]:
### allrows and 1st coumns
students[:,1:2]

array([['Beth'],
       ['78'],
       ['82']], dtype='<U7')

In [93]:
students[:,1:3]

array([['Beth', 'Cathy'],
       ['78', '90'],
       ['82', '79']], dtype='<U7')

In [94]:
### Intrested in all cloumns all clumns for last row
students[-1,:]

array(['71', '82', '79', '92'], dtype='<U7')

In [96]:
students[-3:-1,-2:]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

In [97]:
### all elements in row 0

students[0,...]

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

Iterating Over Arrays:----

In [98]:
Iterate = np.arange(11)**2
Iterate

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [100]:
### Sqaure root of all elememnts
for i in Iterate:
    print( i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [101]:
for i in students:
    print('i=' , i)

i= ['Alice' 'Beth' 'Cathy' 'Dorothy']
i= ['65' '78' '90' '81']
i= ['71' '82' '79' '92']


In [102]:
### Fucntion to access individula element in array is { flatten}
for element in students.flatten():
    print(element)  

Alice
Beth
Cathy
Dorothy
65
78
90
81
71
82
79
92


In [103]:
for element in students.flatten(order= 'F'):
    print(element)  

Alice
65
71
Beth
78
82
Cathy
90
79
Dorothy
81
92


In [104]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [107]:
for i in np.nditer(x, order = 'F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [109]:
for i in np.nditer(x, order = 'F', flags = ['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [111]:
#### [...] is current element in row

for arr in np.nditer(x, order = 'F', op_flags = ['readwrite']):
    arr[...] = arr * arr
    
x

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

Re shaping Array::