<a href="https://colab.research.google.com/github/ragalaa/Directory/blob/master/Array_Manipulation_%26_Multi_Dimensional_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy --upgrade

     |████████████████████████████████| 20.4MB 5.1MB/s 
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:
      Successfully uninstalled numpy-1.16.5


In [0]:
import numpy as np


In [3]:
array_one  = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [4]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two

array([9, 8, 7, 6])

In [5]:
## array shape 3 rows 4 columns with Zeros.
array_of_zeros = np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
## array shape 3 rows 4 columns with ones of specific type with integer.
array_of_ones_int = np.ones((3,4),dtype = np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [9]:
## Empty fucntion with shape
array_empty = np.empty((2,3),dtype = np.int16)
array_empty

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [10]:
### Square matrix 1 along diagnol with 3*3 matrix
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
### arrange to et up specific values with step fucntion with step size 2 until 20
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
## 2 Dimensional array creation with list of list with 2 rows and 3 columns
array_2d = np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [14]:
array_2d.shape

(2, 3)

In [17]:
arrange = np.arange(6)
arrange

array([0, 1, 2, 3, 4, 5])

In [19]:
### reshaping array to 3* 4 ** be care ful if you try to
### reshpe if they don't fit in it will not shape
## To test change to (3,4) requires 12 elements but it ahs only 6
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
### Array fills with same shape and prefills with Ones
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

Printing Arrays--

In [21]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
### 3 dimensional array -- Contains 2 Arrays of Size 3*4
c = np.arange(24).reshape(2,3,4)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [31]:

print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [0]:
## Inorder for the .... to move way and print all elememnts to display we can set the below option
np.set_printoptions(threshold = 10000)
# print(np.arange(10000).reshape(100,100))