<a href="https://colab.research.google.com/github/ragalaa/Directory/blob/master/Portfolio_optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
data = pd.read_csv('Portfolio_Data.csv',sep=",")

In [107]:
data.head()

Date      \nAAPL      \nADBE  ...      \nNFLX     \nORCL     \nSBUX
0  1-Dec-17  164.752060  175.240005  ...  191.960007  45.955631  55.369698
1  1-Nov-17  166.703461  181.470001  ...  187.580002  47.685776  55.451946
2  1-Oct-17  163.977585  175.160004  ...  196.429993  49.279865  52.593998
3  1-Sep-17  149.504440  149.179993  ...  181.350006  46.811028  51.510277
4  1-Aug-17  158.466263  155.160004  ...  174.710007  48.728001  52.376740

[5 rows x 11 columns]

# New Section

In [0]:
### Convert date to format present in 4-Jan-19 to (DD-MM-YYY)
data['Date'] = pd.to_datetime(data['Date'], format='%d-%b-%y')

In [109]:
data.sample(5)

Date      \nAAPL      \nADBE  ...      \nNFLX     \nORCL     \nSBUX
46  2014-02-01   67.853470   68.629997  ...   63.661430  36.010475  32.183372
70  2012-02-01   67.627808   32.889999  ...   15.818571  26.339338  21.420267
13  2016-11-01  105.351799  102.809998  ...  117.000000  38.447659  54.618652
106 2009-02-01   11.134572   16.700001  ...    5.177143  13.651523   3.922260
77  2011-07-01   48.682426   27.709999  ...   37.998573  27.372341  17.552820

[5 rows x 11 columns]

In [0]:
### Sort values by Date
data = data.sort_values(['Date'], ascending=[True])


In [111]:
### Data percentage changes 
### calculate % changes of adjacent rows in the data frame( on numerical columns only)

## data.dtypes return  data types of columns

### step 1 :Filter out all columns whose datatype's are not 'float64 and int64'

returns = data[[key for key in dict(data.dtypes) if dict(data.dtypes)[key] in ['float64', 'int64']]].pct_change()
returns = returns[1:]
returns.head()

\nAAPL    \nADBE     \nCVX  ...    \nNFLX    \nORCL    \nSBUX
130 -0.013065  0.009776 -0.059825  ... -0.012275 -0.042541 -0.115627
129  0.098097  0.062420  0.087156  ...  0.029294  0.103470  0.014887
128  0.074158 -0.003357  0.051785  ... -0.043984  0.036955 -0.010842
127  0.214329  0.060154  0.047564  ... -0.012178  0.030851 -0.071245
126  0.007014 -0.088743  0.041227  ... -0.114612  0.017028 -0.089205

[5 rows x 10 columns]

In [112]:
# lists = []
# for key in dict(data.dtypes):
#     lists.append(key)
# lists    
dict(data.dtypes)

{'\nAAPL': dtype('float64'),
 '\nADBE': dtype('float64'),
 '\nCVX': dtype('float64'),
 '\nGOOG': dtype('float64'),
 '\nIBM': dtype('float64'),
 '\nMDLZ': dtype('float64'),
 '\nMSFT': dtype('float64'),
 '\nNFLX': dtype('float64'),
 '\nORCL': dtype('float64'),
 '\nSBUX': dtype('float64'),
 'Date': dtype('<M8[ns]')}

In [113]:
### set the tickers
stocknames = ["\nAAPL","\nADBE","\nCVX","\nGOOG","\nIBM","\nMDLZ","\nMSFT","\nNFLX","\nORCL","\nSBUX"]
stocknames


['\nAAPL',
 '\nADBE',
 '\nCVX',
 '\nGOOG',
 '\nIBM',
 '\nMDLZ',
 '\nMSFT',
 '\nNFLX',
 '\nORCL',
 '\nSBUX']

In [114]:
stockreturns = returns[stocknames]
stockreturns.head()

\nAAPL    \nADBE     \nCVX  ...    \nNFLX    \nORCL    \nSBUX
130 -0.013065  0.009776 -0.059825  ... -0.012275 -0.042541 -0.115627
129  0.098097  0.062420  0.087156  ...  0.029294  0.103470  0.014887
128  0.074158 -0.003357  0.051785  ... -0.043984  0.036955 -0.010842
127  0.214329  0.060154  0.047564  ... -0.012178  0.030851 -0.071245
126  0.007014 -0.088743  0.041227  ... -0.114612  0.017028 -0.089205

[5 rows x 10 columns]

In [115]:
### Co variance Matrix calculation

Covstocks = stockreturns.cov()
Covstocks

\nAAPL    \nADBE         \nCVX  ...        \nNFLX    \nORCL    \nSBUX
\nAAPL  0.007971  0.003647  1.815202e-03  ...  1.502676e-03  0.002714  0.002811
\nADBE  0.003647  0.006960  1.838044e-03  ...  2.638090e-03  0.002937  0.003553
\nCVX   0.001815  0.001838  3.519740e-03  ...  4.654898e-07  0.001903  0.000840
\nGOOG  0.004046  0.002828  1.641609e-03  ...  1.165909e-03  0.002059  0.002463
\nIBM   0.001867  0.001961  1.242827e-03  ...  1.466549e-03  0.001783  0.001726
\nMDLZ  0.001202  0.001576  8.645164e-04  ...  4.817736e-04  0.001114  0.001918
\nMSFT  0.002966  0.003210  1.761189e-03  ...  2.373813e-03  0.002395  0.002014
\nNFLX  0.001503  0.002638  4.654898e-07  ...  2.855506e-02  0.001493  0.001880
\nORCL  0.002714  0.002937  1.903322e-03  ...  1.492694e-03  0.004398  0.001962
\nSBUX  0.002811  0.003553  8.398749e-04  ...  1.879558e-03  0.001962  0.006219

[10 rows x 10 columns]

In [116]:
### Number  of stocks (n)

n = len(stocknames)
n

10

In [117]:
!pip install CVXOPT

In [0]:
import cvxopt as opt
from cvxopt import matrix, solvers

In [119]:
expectreturn = np.mean(stockreturns)
expectreturn

\nAAPL    0.025202
\nADBE    0.015055
\nCVX     0.008877
\nGOOG    0.014171
\nIBM     0.006863
\nMDLZ    0.009698
\nMSFT    0.012271
\nNFLX    0.044845
\nORCL    0.010706
\nSBUX    0.013125
dtype: float64

In [120]:
### Conver to matrix the expected Return data frame
expectreturn = matrix(expectreturn)
expectreturn

<10x1 matrix, tc='d'>

In [121]:
maxLoss = np.min(stockreturns)
maxLoss

\nAAPL   -0.329559
\nADBE   -0.325057
\nCVX    -0.146979
\nGOOG   -0.184773
\nIBM    -0.205113
\nMDLZ   -0.353223
\nMSFT   -0.165644
\nNFLX   -0.518020
\nORCL   -0.181818
\nSBUX   -0.319879
dtype: float64

In [122]:
maxLoss = -maxLoss
maxLoss

\nAAPL    0.329559
\nADBE    0.325057
\nCVX     0.146979
\nGOOG    0.184773
\nIBM     0.205113
\nMDLZ    0.353223
\nMSFT    0.165644
\nNFLX    0.518020
\nORCL    0.181818
\nSBUX    0.319879
dtype: float64

In [123]:
### 1) Objective Fucntion of Optimuization

Objective = matrix(maxLoss)
Objective

<10x1 matrix, tc='d'>

In [0]:
### 2) seting Up Constaints 

In [124]:
### Sum of weights = 100%
### Define LHS of contraint  1 row , n columns , each value = 1

constraintEqualityLhs = matrix(1.0, (1,n))
constraintEqualityLhs

<1x10 matrix, tc='d'>

In [125]:
### Right hand side of equality
### RHS  1 row, 1 column , value = 1
constraintEqualityRHS = matrix(1.0)
constraintEqualityRHS

<1x1 matrix, tc='d'>

In [126]:
### Non negative contraints -np.identity(n)
### Define LHS as an identity matrix, but multiply by -1(for >=)

contraintsInequalityLhsRow1 = matrix(-np.identity(n))
contraintsInequalityLhsRow1



<10x10 matrix, tc='d'>

In [127]:
### Non negative constraints :matrix(0.0,(n,1))
### define RHS as all zeros,n rows and 1 column

contraintsInequalityRhsRow1 = matrix(0.0,(n,1))
contraintsInequalityRhsRow1

<10x1 matrix, tc='d'>

In [128]:
### one more Inequlaity contraimnts  
#### threshold expected return >= 2%
### LHS as average of returns of each stock - 1 row, 10 columns
contraintsInequalityLhsRow2 = matrix(-np.transpose(np.array(expectreturn)))
contraintsInequalityLhsRow2

<1x10 matrix, tc='d'>

In [129]:
### LHS = -np.ones(1,1)* 2%
contraintsIneuqualityRhsRow2 = matrix(-np.ones((1,1))*0.02)
contraintsIneuqualityRhsRow2

<1x1 matrix, tc='d'>

In [130]:
### concatenate all rows using concatenate into 1 matrix
contraintsInequalityLhsCombined = matrix(np.concatenate((contraintsInequalityLhsRow1,contraintsInequalityLhsRow2),0))
contraintsInequalityLhsCombined


<11x10 matrix, tc='d'>

In [131]:
contraintsInequalityRhsCombined = matrix(np.concatenate((contraintsInequalityRhsRow1,contraintsIneuqualityRhsRow2),0))
contraintsInequalityRhsCombined

<11x1 matrix, tc='d'>

In [132]:
#### Usings SOlver for optimizations
### solving LPP( Liner programming variance )

### Return solution object.

solution = solvers.lp(Objective,contraintsInequalityLhsCombined,contraintsInequalityRhsCombined,constraintEqualityLhs,constraintEqualityRHS)


     pcost       dcost       gap    pres   dres   k/t
 0:  2.7304e-01  2.9556e-01  1e+01  3e+00  4e+00  1e+00
 1:  2.1394e-01  9.4535e-02  7e-01  4e-01  5e-01  4e-03
 2:  1.7927e-01  1.6853e-01  6e-02  5e-02  6e-02  5e-03
 3:  1.7539e-01  1.7058e-01  4e-02  3e-02  3e-02  4e-03
 4:  2.1141e-01  2.1079e-01  7e-02  2e-02  3e-02  6e-03
 5:  2.4099e-01  2.4132e-01  4e-02  1e-02  1e-02  3e-03
 6:  2.4766e-01  2.4772e-01  3e-03  8e-04  9e-04  3e-04
 7:  2.4796e-01  2.4797e-01  5e-04  1e-04  1e-04  5e-05
 8:  2.4810e-01  2.4810e-01  5e-06  1e-06  2e-06  5e-07
 9:  2.4810e-01  2.4810e-01  5e-08  1e-08  2e-08  5e-09
Optimal solution found.


In [133]:
WeightLinear= solution['x']
WeightLinear=np.array(WeightLinear)
WeightLinear
sum(WeightLinear)

array([1.])

In [134]:
### Calculate Risk of Portfolio by 
### It resturn sum-product of weights and max losses

portfolioRiskLinear = np.dot(WeightLinear.T,maxLoss)
portfolioRiskLinear

array([0.24809735])

In [135]:
### Calculate Return of Portfolio by 
### It resturn sum-product of weights and max losses

portfolioReturnLinear = np.dot(WeightLinear.T,maxLoss)
portfolioReturnLinear

array([0.24809735])