<a href="https://colab.research.google.com/github/ragalaa/Directory/blob/master/Quadrartic_Optimization_Risk_return.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
data = pd.read_csv('Portfolio_Data.csv',sep=",")

In [4]:
data.head()

Date      \nAAPL      \nADBE  ...      \nNFLX     \nORCL     \nSBUX
0  1-Jan-19  164.468567  247.820007  ...  339.500000  49.608036  67.218437
1  1-Dec-18  155.871613  226.240005  ...  267.660004  44.590942  63.529015
2  1-Nov-18  175.851181  250.889999  ...  286.130005  48.156242  65.466148
3  1-Oct-18  215.515686  245.759995  ...  301.779999  48.041821  57.174942
4  1-Sep-18  222.290543  269.950012  ...  374.130005  50.717365  55.771816

[5 rows x 11 columns]

# New Section

In [0]:
### Convert date to format present in 4-Jan-19 to (DD-MM-YYY)
data['Date'] = pd.to_datetime(data['Date'], format='%d-%b-%y')

In [6]:
data.sample(5)

Date      \nAAPL      \nADBE  ...      \nNFLX     \nORCL     \nSBUX
121 2008-12-01   10.640865   21.290001  ...    4.270000  15.575384   4.055146
7   2018-06-01  181.644363  243.809998  ...  391.429993  43.170609  47.600578
119 2009-02-01   11.134572   16.700001  ...    5.177143  13.651523   3.922260
20  2017-05-01  146.998749  141.860001  ...  163.070007  43.780102  60.481525
102 2010-07-01   32.072212   28.719999  ...   14.650000  21.004835  10.696387

[5 rows x 11 columns]

In [0]:
### Sort values by Date
data = data.sort_values(['Date'], ascending=[True])


In [8]:
### Data percentage changes 
### calculate % changes of adjacent rows in the data frame( on numerical columns only)

## data.dtypes return  data types of columns

### step 1 :Filter out all columns whose datatype's are not 'float64 and int64'

returns = data[[key for key in dict(data.dtypes) if dict(data.dtypes)[key] in ['float64', 'int64']]].pct_change()
returns = returns[1:]
returns.head()

\nAAPL    \nADBE     \nCVX  ...    \nNFLX    \nORCL    \nSBUX
143 -0.013065  0.009776 -0.059825  ... -0.012275 -0.042541 -0.115627
142  0.098097  0.062420  0.087156  ...  0.029294  0.103470  0.014887
141  0.074158 -0.003357  0.051785  ... -0.043984  0.036955 -0.010842
140  0.214329  0.060154  0.047564  ... -0.012178  0.030851 -0.071245
139  0.007014 -0.088743  0.041227  ... -0.114612  0.017028 -0.089205

[5 rows x 10 columns]

In [9]:
# lists = []
# for key in dict(data.dtypes):
#     lists.append(key)
# lists    
dict(data.dtypes)

{'\nAAPL': dtype('float64'),
 '\nADBE': dtype('float64'),
 '\nCVX': dtype('float64'),
 '\nGOOG': dtype('float64'),
 '\nIBM': dtype('float64'),
 '\nMDLZ': dtype('float64'),
 '\nMSFT': dtype('float64'),
 '\nNFLX': dtype('float64'),
 '\nORCL': dtype('float64'),
 '\nSBUX': dtype('float64'),
 'Date': dtype('<M8[ns]')}

In [10]:
### set the tickers
stocknames = ["\nAAPL","\nADBE","\nCVX","\nGOOG","\nIBM","\nMDLZ","\nMSFT","\nNFLX","\nORCL","\nSBUX"]
stocknames


['\nAAPL',
 '\nADBE',
 '\nCVX',
 '\nGOOG',
 '\nIBM',
 '\nMDLZ',
 '\nMSFT',
 '\nNFLX',
 '\nORCL',
 '\nSBUX']

In [11]:
stockreturns = returns[stocknames]
stockreturns.head()

\nAAPL    \nADBE     \nCVX  ...    \nNFLX    \nORCL    \nSBUX
143 -0.013065  0.009776 -0.059825  ... -0.012275 -0.042541 -0.115627
142  0.098097  0.062420  0.087156  ...  0.029294  0.103470  0.014887
141  0.074158 -0.003357  0.051785  ... -0.043984  0.036955 -0.010842
140  0.214329  0.060154  0.047564  ... -0.012178  0.030851 -0.071245
139  0.007014 -0.088743  0.041227  ... -0.114612  0.017028 -0.089205

[5 rows x 10 columns]

In [12]:
### Co variance Matrix calculation

Covstocks = stockreturns.cov()
Covstocks

\nAAPL    \nADBE     \nCVX  ...    \nNFLX    \nORCL    \nSBUX
\nAAPL  0.008082  0.003602  0.001523  ...  0.001787  0.002676  0.002423
\nADBE  0.003602  0.006779  0.001770  ...  0.003178  0.002924  0.003280
\nCVX   0.001523  0.001770  0.003549  ...  0.000200  0.001836  0.000836
\nGOOG  0.003833  0.002829  0.001640  ...  0.001600  0.002165  0.002252
\nIBM   0.001774  0.002141  0.001431  ...  0.002099  0.001984  0.001734
\nMDLZ  0.001149  0.001611  0.000932  ...  0.000790  0.001278  0.001870
\nMSFT  0.002857  0.003187  0.001711  ...  0.002571  0.002410  0.001897
\nNFLX  0.001787  0.003178  0.000200  ...  0.028123  0.001793  0.001465
\nORCL  0.002676  0.002924  0.001836  ...  0.001793  0.004370  0.001930
\nSBUX  0.002423  0.003280  0.000836  ...  0.001465  0.001930  0.006015

[10 rows x 10 columns]

In [16]:
### Converting data frame to matrix representation
!pip install CVXOPT
import cvxopt as opt
from cvxopt import matrix, solvers
Covstocks = matrix(np.array(Covstocks))
Covstocks

<10x10 matrix, tc='d'>

In [19]:
### Number  of stocks (n)

n = len(stocknames)
n

10

In [17]:
### 1) Objective Fucntion of Optimuization

Objective = Covstocks
Objective

<10x10 matrix, tc='d'>

In [20]:
### Linear Objective = np.zeros
### The linear portion of the objective fucntion = all Zeros,n rows, 1 column
vector = matrix(np.zeros((n,1)))
vector

<10x1 matrix, tc='d'>

In [23]:
expectreturn = np.mean(stockreturns)
### Conver to matrix the expected Return data frame
expectreturn = matrix(expectreturn)
expectreturn

<10x1 matrix, tc='d'>

In [0]:
### 2) seting Up Constaints 

In [42]:
### 
###Optimizer to short on some stocks

# constraintInEqualityLhs = matrix(-np.transpose(np.array(expectreturn)))
# constraintInEqualityLhs

###2.2For long stratergy

constraintInEquLhslong = matrix(-np.identity(n))
constraintInEquLhslong



<10x10 matrix, tc='d'>

In [25]:
### Right hand side of equality
### Expected return will be bumped to >= 5%
### Higher risk since shortselling stocks is allowed, so demand higher return
constraintsInEqualityRHS = matrix(-np.ones((1,1))**0.05)
constraintsInEqualityRHS

<1x1 matrix, tc='d'>

In [26]:
### Equality Constraints
### Expected Return >= 5%
## Force sum of all portfolio weights to be 1

contraintsequalityLhs = matrix(1.0,(1,n))
contraintsequalityLhs



<1x10 matrix, tc='d'>

In [27]:
### Non negative constraints :matrix(0.0,(n,1))
### define RHS as all zeros,n rows and 1 column

contraintsequalityRhs = matrix(1.0)
contraintsequalityRhs

<1x1 matrix, tc='d'>

In [28]:
#### Usings SOlver for optimizations
### solving Qp( Quadratic programming variance )

### Return solution object.

solution = solvers.qp(Objective,vector , constraintInEqualityLhs, constraintsInEqualityRHS ,contraintsequalityLhs, constraintsInEqualityRHS)


     pcost       dcost       gap    pres   dres
 0:  4.0382e-02  8.9539e-01  9e-01  2e+00  8e-18
 1:  2.1343e-01  1.9561e+00  2e-02  8e-01  3e-17
 2:  7.2074e+00  5.4180e+00  2e+00  8e-15  1e-15
 3:  5.5665e+00  5.5290e+00  4e-02  3e-15  1e-16
 4:  5.5294e+00  5.5290e+00  4e-04  4e-15  1e-16
 5:  5.5290e+00  5.5290e+00  4e-06  2e-15  3e-16
Optimal solution found.


In [32]:
WeightQuad= solution['x']
WeightQuad

<10x1 matrix, tc='d'>

In [33]:
### solver tellint to go 23.3 % on apple
## and short on chevron an other wiyh negative

WeightQuad=np.array(WeightQuad)
WeightQuad


array([[ 23.37156967],
       [  5.99907447],
       [ -0.94527449],
       [ -1.43790677],
       [-33.23896297],
       [ -1.1221376 ],
       [ -9.05681612],
       [ 15.19000969],
       [ -4.24972261],
       [  4.49016672]])

In [34]:
sum(WeightQuad)

array([-1.])

In [35]:
### Calculate Risk of Portfolio by 
### It resturn sum-product of weights and max losses

portfolioRiskQuad = np.dot(np.dot(WeightQuad.T,Covstocks),WeightQuad)
portfolioRiskQuad

array([[11.05809005]])

In [36]:
### Calculate Return of Portfolio by 
### It resturn sum-product of weights and max losses
### Two nested calls to numpy.dot to compute w_transpose* cov * w

portfolioReturnQuad = np.dot(expectreturn.T,WeightQuad)
portfolioReturnQuad

array([[1.00000034]])